// Auto-generated by shelley.exe.dev/cmd/go2ts.go
// Do not edit manually - regenerate with: go run ./cmd/go2ts -o ui/src/generated-types.ts

// DO NOT EDIT. This file is automatically generated.

export interface Conversation {
  conversation_id: string;
  slug: string | null;
  user_initiated: boolean;
  created_at: string;
  updated_at: string;
  cwd: string | null;
  archived: boolean;
  parent_conversation_id: string | null;
  model: string | null;
  conversation_options: string;
  current_generation: number;
  agent_working: boolean;
  tags: string;
  is_draft: boolean;
  draft: string;
  queued_messages: string;
  turn_interrupted: boolean;
}

export interface Usage {
  input_tokens: number;
  cache_creation_input_tokens: number;
  cache_read_input_tokens: number;
  output_tokens: number;
  cost_usd: number;
  model?: string;
  url?: string;
  start_time?: string | null;
  end_time?: string | null;
}

export interface ApiMessageForTS {
  message_id: string;
  conversation_id: string;
  sequence_id: number;
  type: string;
  llm_data?: string | null;
  user_data?: string | null;
  usage_data?: string | null;
  other_usage_data?: string | null;
  created_at: string;
  display_data?: string | null;
  generation: number;
  end_of_turn?: boolean | null;
  llm_api_url?: string | null;
  model_name?: string | null;
  forked_from_message_id?: string | null;
  user_email?: string | null;
}

export interface ConversationStateForTS {
  conversation_id: string;
  working: boolean;
  model?: string;
}

export interface NotificationEventForTS {
  type: EventType;
  conversation_id: string;
  timestamp: string;
  payload?: any;
}

export interface DiskSpaceStatus {
  episode_id: number;
  revision: number;
  active: boolean;
  critical: boolean;
  dismissed: boolean;
  available_bytes: number;
}

export interface StreamResponseForTS {
  conversation_id?: string;
  messages?: ApiMessageForTS[] | null;
  conversation?: Conversation | null;
  conversation_state?: ConversationStateForTS | null;
  heartbeat?: boolean;
  notification_event?: NotificationEventForTS | null;
  disk_space_status?: DiskSpaceStatus | null;
  max_sequence_id?: number;
}

export interface ConversationParticipant {
  email: string;
  message_count: number;
}

export interface ConversationWithStateForTS {
  conversation_id: string;
  slug: string | null;
  user_initiated: boolean;
  created_at: string;
  updated_at: string;
  cwd: string | null;
  archived: boolean;
  parent_conversation_id: string | null;
  model: string | null;
  conversation_options: string;
  current_generation: number;
  agent_working: boolean;
  tags: string;
  is_draft: boolean;
  draft: string;
  queued_messages: string;
  turn_interrupted: boolean;
  working: boolean;
  git_repo_root?: string;
  git_worktree_root?: string;
  git_commit?: string;
  git_subject?: string;
  subagent_count: number;
  preview?: string;
  preview_updated_at?: string;
  search_snippet?: string;
  max_sequence_id: number;
  participants?: ConversationParticipant[] | null;
}

export type MessageType =
  | "user"
  | "agent"
  | "tool"
  | "error"
  | "system"
  | "gitinfo"
  | "warning"
  | "modelchange"
  | "slug";

export type EventType = string;
