// A command line tool for generating typescript type declarations from go
// struct types.
//
// Example:
//
//	go run ./cmd/go2ts -o ui/src/generated-types.ts
package main

import (
	"flag"
	"fmt"
	"os"
	"time"

	"go.skia.org/infra/go/go2ts"
	"shelley.exe.dev/db"
	"shelley.exe.dev/db/generated"
	"shelley.exe.dev/llm"
	"shelley.exe.dev/server/diskspace"
	"shelley.exe.dev/server/notifications"
)

func main() {
	outputPath := flag.String("o", "", "Path to the output TypeScript file.")
	flag.Parse()

	if *outputPath == "" {
		fmt.Println("Usage: go run ./cmd/go2ts -o <output-file>")
		os.Exit(1)
	}

	generator := TS()

	w, err := os.Create(*outputPath)
	if err != nil {
		fmt.Printf("error: %v\n", err)
		os.Exit(1)
	}
	defer w.Close()

	fmt.Fprintf(w, "// Auto-generated by shelley.exe.dev/cmd/go2ts.go\n")
	fmt.Fprintf(w, "// Do not edit manually - regenerate with: go run ./cmd/go2ts -o ui/src/generated-types.ts\n\n")
	generator.Render(w)
}

// TS returns a Go2TS generator for go types we want to use in TypeScript.
func TS() *go2ts.Go2TS {
	generator := go2ts.New()

	// Database message types enum
	generator.AddMultipleUnion(
		[]db.MessageType{
			db.MessageTypeUser,
			db.MessageTypeAgent,
			db.MessageTypeTool,
			db.MessageTypeError,
			db.MessageTypeSystem,
			db.MessageTypeGitInfo,
			db.MessageTypeWarning,
			db.MessageTypeModelChange,
			db.MessageTypeSlug,
		},
	)

	// Database struct types
	generator.AddMultiple(
		generated.Conversation{},
		llm.Usage{},
	)

	generator.AddMultiple(
		apiMessageForTS{},
		streamResponseForTS{},
		conversationWithStateForTS{},
		notificationEventForTS{},
		diskspace.DiskSpaceStatus{},
	)

	// Generate clean nominal types
	generator.GenerateNominalTypes = true

	return generator
}

type apiMessageForTS struct {
	MessageID      string    `json:"message_id"`
	ConversationID string    `json:"conversation_id"`
	SequenceID     int64     `json:"sequence_id"`
	Type           string    `json:"type"`
	LlmData        *string   `json:"llm_data,omitempty"`
	UserData       *string   `json:"user_data,omitempty"`
	UsageData      *string   `json:"usage_data,omitempty"`
	OtherUsageData *string   `json:"other_usage_data,omitempty"`
	CreatedAt      time.Time `json:"created_at"`
	DisplayData    *string   `json:"display_data,omitempty"`
	Generation     int64     `json:"generation"`
	EndOfTurn      *bool     `json:"end_of_turn,omitempty"`

	LLMAPIURL           *string `json:"llm_api_url,omitempty"`
	ModelName           *string `json:"model_name,omitempty"`
	ForkedFromMessageID *string `json:"forked_from_message_id,omitempty"`
	UserEmail           *string `json:"user_email,omitempty"`
}

type conversationStateForTS struct {
	ConversationID string `json:"conversation_id"`
	Working        bool   `json:"working"`
	Model          string `json:"model,omitempty"`
}

type conversationWithStateForTS struct {
	ConversationID       string                       `json:"conversation_id"`
	Slug                 *string                      `json:"slug"`
	UserInitiated        bool                         `json:"user_initiated"`
	CreatedAt            string                       `json:"created_at"`
	UpdatedAt            string                       `json:"updated_at"`
	Cwd                  *string                      `json:"cwd"`
	Archived             bool                         `json:"archived"`
	ParentConversationID *string                      `json:"parent_conversation_id"`
	Model                *string                      `json:"model"`
	ConversationOptions  string                       `json:"conversation_options"`
	CurrentGeneration    int64                        `json:"current_generation"`
	AgentWorking         bool                         `json:"agent_working"`
	Tags                 string                       `json:"tags"`
	IsDraft              bool                         `json:"is_draft"`
	Draft                string                       `json:"draft"`
	QueuedMessages       string                       `json:"queued_messages"`
	TurnInterrupted      bool                         `json:"turn_interrupted"`
	Working              bool                         `json:"working"`
	GitRepoRoot          string                       `json:"git_repo_root,omitempty"`
	GitWorktreeRoot      string                       `json:"git_worktree_root,omitempty"`
	GitCommit            string                       `json:"git_commit,omitempty"`
	GitSubject           string                       `json:"git_subject,omitempty"`
	SubagentCount        int64                        `json:"subagent_count"`
	Preview              string                       `json:"preview,omitempty"`
	PreviewUpdatedAt     string                       `json:"preview_updated_at,omitempty"`
	SearchSnippet        string                       `json:"search_snippet,omitempty"`
	MaxSequenceID        int64                        `json:"max_sequence_id"`
	Participants         []db.ConversationParticipant `json:"participants,omitempty"`
}

type streamResponseForTS struct {
	ConversationID    string                     `json:"conversation_id,omitempty"`
	Messages          []apiMessageForTS          `json:"messages,omitempty"`
	Conversation      *generated.Conversation    `json:"conversation,omitempty"`
	ConversationState *conversationStateForTS    `json:"conversation_state,omitempty"`
	Heartbeat         bool                       `json:"heartbeat,omitempty"`
	NotificationEvent *notificationEventForTS    `json:"notification_event,omitempty"`
	DiskSpaceStatus   *diskspace.DiskSpaceStatus `json:"disk_space_status,omitempty"`
	MaxSequenceID     int64                      `json:"max_sequence_id,omitempty"`
}

type notificationEventForTS struct {
	Type           notifications.EventType `json:"type"`
	ConversationID string                  `json:"conversation_id"`
	Timestamp      string                  `json:"timestamp"`
	Payload        any                     `json:"payload,omitempty"`
}
